#version: "3.8"
services:
  web:
    build: docker/web
    command: /bin/sh -c "git config --global --add safe.directory /var/www/html && cd /var/www/html && git pull && apache2-foreground && npm install && npm run build"

    depends_on:
      - db
    ports:
      - "80:80"
  db:
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
volumes:
  db:
